### ISSUE TITLE
[parrot] The web site doesn't work with Edge

### ISSUE THREAD

**Issue by mathieu-benoit** [Azure/phippyandfriends#10]
It's working with Chrome for example but not with Edge. 

![image](https://user-images.githubusercontent.com/11720844/47216007-74d9dc00-d371-11e8-970d-1cfc47cc59bc.png)

We could see that's an error in the `deamon.js` file:
![image](https://user-images.githubusercontent.com/11720844/47216054-a9e62e80-d371-11e8-9b6b-27384d2f9149.png)

**Comment by mathieu-benoit** [comment]
FYI @sabbour @bradygmsft

**Comment by sabbour** [comment]
Let me have a look at this. @bradygmsft is changing roles. @mathieu-benoit do you have it publicly deployed somewhere to check?

**Comment by mathieu-benoit** [comment]
@sabbour, sending you this by email internally.

**Comment by sabbour** [comment]
@mathieu-benoit  Looks like Edge doesn't like a `catch` statement without an object. I didn't try the fix below as I don't have Edge because I'm running on a Mac.

Can you change this line:

https://github.com/Azure/phippyandfriends/blob/7ae69692dee92ece93f280fc2f52a95a792f00f6/parrot/wwwroot/scripts/daemon.js#L35

to be this instead and let me know if it fixes it? 

`try { ko.applyBindings(viewModel); } catch (err) {console.error(err); }`

**Comment by sabbour** [comment]
This is the upstream issue in Edge's javascript engine https://github.com/Microsoft/ChakraCore/pull/5310

**Comment by sabbour** [comment]
@mathieu-benoit thanks for the report. It seems that Edge doesn't support the try/catch syntax without an identifier (https://github.com/Microsoft/ChakraCore/pull/5310).

Can you please edit the line below

https://github.com/Azure/phippyandfriends/blob/7ae69692dee92ece93f280fc2f52a95a792f00f6/parrot/wwwroot/scripts/daemon.js#L35

to be

```javascript
try { ko.applyBindings(viewModel); } catch (err) { console.error(err); }
```

and let me know if it works for you? Sorry I don't have Edge to test it as I'm running on a Mac.

**Comment by mathieu-benoit** [comment]
Just implemented here https://github.com/Azure/phippyandfriends/pull/12 and tested, it works now like a charm, good catch!
