### ISSUE TITLE
Add some credits

### ISSUE THREAD

**Issue by ThorstenHans** [Azure/phippyandfriends#6]
Maybe I've missed that point but if I recall correctly, Phippy was introduced in 2016 from Matt Butcher at Deis.

Their website says

> The guide was written by Matt Butcher (@technosophos), Illustrated by Bailey Beougher, and designed by Karen Chu.

https://deis.com/blog/2016/kubernetes-illustrated-guide/

So it would be fair to pay some respect to the author

**Comment by bradygmsft** [comment]
@ThorstenHans we did mention the original story in the introduction paragraph on the readme. I noticed that link has been moved to a "read-aloud" video of the story rather than the original blog post, so I added a credits section, which was one of the requests @Stellaleigh had made earlier that I'd not been able to get to. I added the section, a link to @technosophos's twitter and blog post, and called him out in the introduction **and** credits section. Thanks so much for reporting this issue, and for giving me the opportunity to thank Matt and the DEIS crew for the story.
